baseURL = "/itmap"
languageCode = "ru-RU"
title = "Карта программного обеспечения Свердловской области"
theme = ""

[params]
  description = "Интерактивная карта производителей программного обеспечения из Свердловской области"
  author = "Свердловская область"
